//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAPII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercise_Plan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exercise_Plan()
        {
            this.Exercise_Plan_Day = new HashSet<Exercise_Plan_Day>();
        }
    
        public int Exercise_Plan_ID { get; set; }
        public string Exercise_Plan_Name { get; set; }
        public Nullable<int> Exercise_Plan_Type_ID { get; set; }
    
        public virtual Exercise_Plan_Type Exercise_Plan_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exercise_Plan_Day> Exercise_Plan_Day { get; set; }
    }
}
